name: CI

on:
  watch:
    types: [started]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Star notification
        run: curl -XPOST -s -o /dev/null ${{ secrets.NOTIFICATION_URL }}
