name: CI

on: []

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - name: Failure notification
        if: always()
        run: curl -XPOST ${{ secrets.NOTIFICATION_URL }}
